### PR TITLE
Fix destination path creation.

### PR DESCRIPTION
**Pull request by pravic**
Use convenient clone behavior:

* default: `cargo clone <name>` clones a source crate into `$PWD/name` path.
* with `--prefix <path>` clones crate into `<path>` (relative or absolute).
* cloning into an existing directory is only allowed if the directory is empty.

refs #3

### CODE REVIEW

**Comment by JanLikar** [comment]
Awesome, thank you! I will review the patch as soon as possible, but it looks great at a first glance.

**Comment by pravic** [comment]
> but it looks great at a first glance.
May be we need a `Cloning into '<path>'...` message also. Currently it shows nothing.

**Comment by JanLikar** [comment]
I don't have a strong opinion on this. It could be useful, but on the other hand, I feel CLI utils should stay quiet, unless they have something unexpected to report. What do you think? Maybe we should put this behind the "verbose" flag.

**Comment by pravic** [comment]
Nah, it is better to leave it as is then.

**Comment by JanLikar** [comment]
Sure, that's fine.

**Comment by smvoss** [comment]
Cargo uses `--root` for this feature. You might consider changing the flag to match cargo.


cargo install --help:
`--root DIR                Directory to install packages into`

**Comment by pravic** [comment]
@smvoss Sounds reasonable. If @JanLikar doesn't mind to break compatibility (or just to add it as an alias).

**Comment by JanLikar** [comment]
`--root` makes perfect sense for `cargo install`, I'm not sure it does for `cargo clone`.

I was thinking about something more like `cargo clone [options] <crate> [path]`.

**Comment by smvoss** [comment]
That's a good point. I think personally I'm not a fan of `--prefix`, but maybe `--output-dir`|`-o`? Optional path could work too, a bit less standard though, I think.

**Comment by pravic** [comment]
You know, since it is `clone` I would go with `git clone` behavior which is `git clone <URL> [PATH]`.

**Comment by smvoss** [comment]
Oh right, I honestly don't use that clone syntax too often so I forget about it. Could work for sure

**Comment by smvoss** [comment]
@JanLikar @pravic Think this should be a new issue instead of tacking onto this PR?

**Comment by pravic** [comment]
> I will review the patch as soon as possible
:)

**Comment by smvoss** [comment]
Oh, I was specifically talkin about the clone syntax, not what you have done already!

**Comment by dpc** [comment]
Can this be landed?

**Comment by JanLikar** [comment]
Sorry for the delay, I've neglected this crate for too long.

I will merge this PR as soon as someone rebases it. If I'll have some time to spare, I might do it myself.

**Comment by JanLikar** [comment]
@pravic hit me up on j@ctrl-d.io, let's do something about this.

**Comment by pravic** [comment]
I'll rebase it

**Pull request closed without merging**
